/* export const FETCH_CONTRACTS_REQUEST = "FETCH_CONTRACTS_REQUEST";
export const FETCH_CONTRACTS_SUCCESS = "FETCH_CONTRACTS_SUCCESS";
export const FETCH_CONTRACTS_FAILURE = "FETCH_CONTRACTS_FAILURE"; */

export const LOAD_CONTRACT = "LOAD_CONTRACT";
export const LOAD_CONTRACT_ERROR = "LOAD_CONTRACT_ERROR";
